name: mlflow_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.0
  - pip<=23.2.1
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - pip:
    - mlflow==2.17.2
    - cloudpickle==2.2.1
    - diffusers==0.31.0
    - accelerate==0.31.0
    - attrs==22.1.0
    - bcrypt==3.2.0
    - boto3==1.34.39
    - configparser==5.2.0
    - defusedxml==0.7.1
    - dill==0.3.6
    - lz4==4.3.2
    - numpy==1.23.5
    - nvidia-ml-py==12.555.43
    - pandas==1.5.3
    - pyopenssl==23.2.0
    - scipy==1.11.1
    - transformers==4.41.2